### ISSUE TITLE
Stuck on loading and not encoding.

### ISSUE THREAD

**Issue by Hunk4TH** [pathartl/BananaSplit#20]
I just discovered this tool earlier and its just what I've been looking for to split a lot of classic NickToons and Cartoon Network series I have! However when loading some it just says stuck on the loading screen. When it does load a file and add them to the queue it and select encode and it doesn't do anything. Using Windows 10 x64.

Even tried on Linux with the same result.

**Comment by trumanswaltz** [comment]
I am also having this problem with Windows 10 and linux

**Comment by ricardosabino** [comment]
It comes a bit late but so that others can see it if they run into the same issue. This was happening to me too, for me it was some encoding format not supported by FFMPEG so I had to re-encode the files with VLC and then FFMPEG worked correctly. I've been improving the tool on the side and I've added a log window which shows output from FFMPEG. I've submitted a PR for something else and plan on submitting another one for the logging but I'm not sure if there's anyone maintaining this anymore. If you want to check it out in the meanwhile you can do it here: [https://github.com/ricardosabino/BananaSplit/tree/dev](https://github.com/ricardosabino/BananaSplit/tree/dev)

**Comment by pathartl** [comment]
New build has been published: [v3.2.1](https://github.com/pathartl/BananaSplit/releases/tag/v3.2.1)
