### ISSUE TITLE
App is a complete mess

### ISSUE THREAD

**Issue by nv4** [pathartl/BananaSplit#21]
Why is this app so buggy? Has it always been like this? Or did it just get worse after moving from Electron to .NET Core? I can't accomplish a single task with it. Attempting to open settings causes unhandled exceptions half the time. Reading a folder works after 5 tries. After selecting the timestamps on 30 different files to insert Matroska chapter markers on, hitting Process Queue immediately crashes the app. No cache or logs to be found anywhere.  Half an hour's worth of processing gone in thin air. Please make previous releases available again (if they were any better).

**Comment by pathartl** [comment]
Thanks for the submission. I haven't had much time recently to dig more into the application. The newest version is the least buggy version available, believe it or not. There's a lot of challenges with processing videos like this.

I'll take your feedback and investigate further. I haven't had a chance to look over the code since the rewrite.

**Comment by ricardosabino** [comment]
Hi, comes a bit late but I've submitted a PR that might fix some of these issues (specially with the Settings crash). I've also added logging functionality which I have in my repo and pretend to submit a PR for it once the other one gets approved.

**Comment by pathartl** [comment]
@ricardosabino 's PR has been approved and merged and included in the 3.1.0 release. Closing this issue.
